name: zohodesk_portal_configuration
description: ASAP Flutter plugin for Configuration for mobile app configurations.
version: 1.1.5
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  
  zohodesk_portal_apikit: 1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zoho.desk.asap.configuration.zohodesk_portal_configuration
        pluginClass: ZohodeskPortalConfigurationPlugin
      ios:
        pluginClass: ZohodeskPortalConfigurationPlugin