name: zohodesk_portal_gc
description: Flutter plugin for ZohoDesk Guided conversation written around native GC SDKs
version: 2.0.2
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  
  zohodesk_portal_apikit: 2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zoho.desk.asap.gc.zohodesk_portal_gc
        pluginClass: ZohodeskPortalGcPlugin
      ios:
        pluginClass: ZohodeskPortalGcPlugin