name: zohodesk_portal_services
description: Zoho Desk Portal Services Flutter plugin, this flutter plugin comes with Flutter Core along with SalesIQ for agent chat.
version: 1.0.6
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  zohodesk_portal_core: 1.0.6
  zohodesk_portal_chat: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zoho.desk.asap.services.zohodesk_portal_services
        pluginClass: ZohodeskPortalServicesPlugin
      ios:
        pluginClass: ZohodeskPortalServicesPlugin