name: zohodesk_portal_chat
description: Zohodesk agent chat flutter plugin.
version: 1.0.6
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  zohodesk_portal_apikit: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zoho.desk.asap.chat.zohodesk_portal_chat
        pluginClass: ZohodeskPortalChatPlugin
      ios:
        pluginClass: ZohodeskPortalChatPlugin

