name: zohodesk_portal_siq
description: Zohodesk agent chat flutter plugin.
version: 2.5.0
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  zohodesk_portal_apikit: 2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zoho.desk.asap.siq.zohodesk_portal_siq
        pluginClass: ZohodeskPortalSiqPlugin
      ios:
        pluginClass: ZohodeskPortalSiqPlugin

