name: zohodesk_portal_ticket
description: ASAP Flutter plugin for ASAP Tickets for mobile app configurations.
version: 1.0.9
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  zohodesk_portal_apikit: 1.0.9
  zohodesk_portal_submit_ticket: 1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zoho.desk.asap.ticket.zohodesk_portal_ticket
        pluginClass: ZohodeskPortalTicketPlugin
      ios:
        pluginClass: ZohodeskPortalTicketPlugin
