name: zohodesk_portal_kb
description: Flutter plugin for Zoho Desk ASAP KB module
version: 1.0.7
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  zohodesk_portal_configuration: 1.0.7
  zohodesk_portal_apikit: 1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zoho.desk.asap.kb.zohodesk_portal_kb
        pluginClass: ZohodeskPortalKbPlugin
      ios:
        pluginClass: ZohodeskPortalKbPlugin
