name: zohodesk_portal_community
description: ASAP Community module Flutter Plugin
version: 2.0.4
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  zohodesk_portal_apikit: 2.0.4
  zohodesk_portal_configuration: 2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.zoho.desk.asap.community.zohodesk_portal_community
        pluginClass: ZohodeskPortalCommunityPlugin
      ios:
        pluginClass: ZohodeskPortalCommunityPlugin
